name: Publish code coverage to Coveralls

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v3
      with:
        packages: zig,kcov
        script: |
          zig build tests -Doptimize=Debug
          ls
          kcov --clean --exclude-pattern=nix,usr,local,cache,_tests.cpp --coveralls-id=${{ secrets.COVERALLS_REPO_TOKEN }} kcov-output ./zig-out/bin/boislib_tests
